[project]
name = "chrome-control"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.12.9",
    "psutil",
]

[tool.uv.sources]
psutil = { workspace = true }

[tool.uv.workspace]
members = [
    "dummy-psutil",
]
